language: python
python:
  - "2.7"

install:
  - pip install --use-mirrors pep8 pyflakes
  - pip install --use-mirrors cython
  - python setup.py install

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -n -w --no-diffs troposphere; fi
  - pep8 --version
  - pep8 coro old test

script:
  - (cd test; sh -e runner)
